### PR TITLE
Standard and Exam Version Release 0.2.1 with fixed pom.xml

### PR DESCRIPTION
**Pull request by LineStettler**
Still the same merge conflicts, but the project should be able to built and run now

### CODE REVIEW

**Comment by THS-on** [comment]
Same issue.
Changed  in build.xml `ch.fhnw.lernstickwelcome.Welcome` to `ch.fhnw.lernstickwelcome.controller.WelcomeApplication` but now i get this error:
```
Mai 14, 2017 3:28:42 PM ch.fhnw.lernstickwelcome.controller.WelcomeApplication start
SCHWERWIEGEND: Couldn't initialize GUI
java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at ch.fhnw.lernstickwelcome.util.FXMLGuiLoader.loadScene(FXMLGuiLoader.java:197)
	at ch.fhnw.lernstickwelcome.util.FXMLGuiLoader.<init>(FXMLGuiLoader.java:90)
	at ch.fhnw.lernstickwelcome.controller.WelcomeApplication.start(WelcomeApplication.java:78)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by THS-on** [comment]
I've build lernstickWelcome also with maven (form backports) on Lernstick. Same issue if you try to run the .jar manually. 
After some debugging I found that path for FXLGuiLoader is a relative "../view/main.fxml" and after that the location is right (file:/home/user/lernstickWelcome/build/classes/ch/fhnw/lernstickwelcome/view/main.fxml)
But in the final jar it is (/ch/fhnw/lernstickwelcome/view/main.fxml)
It seems that this is not working if the project is packaged into a jar:
```
FXMLLoader loader = new FXMLLoader(getClass().getResource(path), rb);
``` 
(https://github.com/valendinosaurus/lernstickWelcome/blob/master/src/ch/fhnw/lernstickwelcome/util/FXMLGuiLoader.java#L196)

**Comment by THS-on** [comment]
If all `../view`  in `FXMLGuiLoader.java` are replaced with `/ch/fhnw/lernstickwelcome/view` the application works as intended if build with Netbeans 8.
I don't know what the best solution to this problem is because I'm not a java programmer.

**Comment by THS-on** [comment]
If the jar is build with `mvn package` instead of ant which downloads lernstickTools from Github there is an other issue: 
```
AM FEINSTEN: systemSize: 5.139.743.232
Mai 14, 2017 9:28:33 PM ch.fhnw.util.Partition getPartitionFromMountPoint
FEIN: mountPoint: "/lib/live/mount/medium"
Exception in Application start method
Exception in Application stop method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at ch.fhnw.util.Partition.getPartitionFromMountPoint(Partition.java:88)
	at ch.fhnw.util.StorageTools.getSystemStorageDevice(StorageTools.java:64)
	at ch.fhnw.lernstickwelcome.model.WelcomeModelFactory.getSystemStorageDevice(WelcomeModelFactory.java:74)
	at ch.fhnw.lernstickwelcome.model.systemconfig.SystemconfigTask.getPartitions(SystemconfigTask.java:204)
	at ch.fhnw.lernstickwelcome.model.systemconfig.SystemconfigTask.<init>(SystemconfigTask.java:106)
	at ch.fhnw.lernstickwelcome.model.WelcomeModelFactory.getSystemTask(WelcomeModelFactory.java:150)
	at ch.fhnw.lernstickwelcome.controller.WelcomeController.loadStandardEnvironment(WelcomeController.java:118)
	at ch.fhnw.lernstickwelcome.controller.WelcomeApplication.start(WelcomeApplication.java:153)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	... 1 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name ch/fhnw/util/Strings, locale de_DE
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at ch.fhnw.util.LernstickFileTools.<clinit>(LernstickFileTools.java:35)
	... 17 more
Exception running application ch.fhnw.lernstickwelcome.controller.WelcomeApplication
``` 
What build system should be used Ant or maven? Do you guys have a bug tracker because I think this pull request is not the right place to report issues.

**Comment by LineStettler** [comment]
mvn should be used. we found an other issue as well, and still are working on it. and we don't have a bug tracker... would a issue be a better place than the pull request?

**Comment by THS-on** [comment]
Ok. You could enable the bug tracker at https://github.com/valendinosaurus/lernstickWelcome.   
I think it's better if I can open issues on your repository instead of imedias. If the pull request is not working and somebody is working on it, it's a good idea to add `[WIP]` so another person can see that this is work in progress.

**Comment by LineStettler** [comment]
I am not the owner of the repository and Issues are disabled at the moment. But we will create an issue as soon as possible

**Comment by LineStettler** [comment]
https://github.com/valendinosaurus/lernstickWelcome/issues/4

**Pull request closed without merging**
